name: Portfolio site deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm packages
        run: npm install

      - name: Build project
        run: npm run build

      - name: upload build files
        uses: actions/cache@v3
        with:
          path: ./build
          key: production-build-${{ github.sha }}

  deploy:
    name: Deploy
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build files
        uses: actions/cache@v3
        with:
          path: ./build
          key: production-build-${{ github.sha }}
          restore-keys: |
            production-build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
